Repository falcosecurity/falco-website, pull requests merged in 2019-11, with the labels that each got.

#99 Updating probe loader script
  content/en/docs/event-sources/kernel-module.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#100 Blog for security hub
  content/en/blog/cloud-native-security-hub.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#101 fix: Fix broken configuration link
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: approved, area/documentation, dco-signoff: yes, kind/bug, lgtm, size/XS

#103 Point to the official proposal
  content/en/blog/cloud-native-security-hub.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#104 Hub blog 3
  content/en/blog/cloud-native-security-hub.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#105 Fix url
  content/en/blog/cloud-native-security-hub.md
Labels: approved, dco-signoff: yes, lgtm, size/M
