Repository falcosecurity/falco-website, pull requests merged in 2019-10, with the labels that each got.

#82 add a shortcode + doc page to display changelog from github releases
  content/en/docs/changelog.md
  themes/falco-fresh/layouts/shortcodes/changelog.html
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/S

#85 fix(themes/falco-fresh): filter out duplicated page sections
  themes/falco-fresh/layouts/partials/docs/dashboard.html
Labels: approved, dco-signoff: yes, kind/bug, kind/cleanup, kind/user-interface, lgtm, size/XS

#89 Edited gRPC Doc for Clarity and Structure
  content/en/docs/grpc/_index.md
  content/en/docs/grpc/client-go.md
  content/en/docs/grpc/outputs.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#90 fix: restore highlights for grpc
  content/en/docs/grpc/_index.md
  content/en/docs/grpc/client-go.md
  content/en/docs/grpc/outputs.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#91 Use backtick-based highlighting
  content/en/docs/grpc/_index.md
  content/en/docs/grpc/client-go.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#93 Add docs for K8s PSP Support
  content/en/docs/psp_support/_index.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/L
