Repository falcosecurity/falco-website, pull requests merged in 2019-09, with the labels that each got.

#73 new: owners file
  OWNERS
Labels: dco-signoff: yes, lgtm, size/S

#75 Fix link to helm chart configuration values
  content/en/docs/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#76 doc: issue and pull request template
  .github/ISSUE_TEMPLATE/blog-content-request.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/content-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#81 update(falco-website): prepare for release v0.17.1
  config.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS
