Repository falcosecurity/falco-website, pull requests merged in 2020-02, with the labels that each got.

#124 new: replace dev branch with master branch in the docs
  .github/PULL_REQUEST_TEMPLATE.md
  content/en/blog/falco-security-audit.md
  content/en/docs/_index.md
  content/en/docs/alerts/_index.md
  content/en/docs/event-sources/kernel-module.md
  content/en/docs/event-sources/kubernetes-audit.md
  content/en/docs/event-sources/sample-events.md
  content/en/docs/source.md
  content/zh/docs/_index.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#128 Update Changelog aesthetic
  content/en/docs/changelog.md
  themes/falco-fresh/assets/style.sass
  themes/falco-fresh/layouts/shortcodes/changelog.html
Labels: approved, dco-signoff: yes, lgtm, size/M

#129 Remove unnecessary resources dir
  themes/falco-fresh/resources/_gen/assets/sass/style.sass_cf66e63debe6917c04534d6c7b66f623.content
  themes/falco-fresh/resources/_gen/assets/sass/style.sass_cf66e63debe6917c04534d6c7b66f623.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#133 new: document grpc flags
  data/config.yaml
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/M

#135 Update sha256sum for curl | bash installer
  config.yaml
Labels: approved, area/documentation, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#122 fix: wrong word for docs/source.md
  content/en/docs/source.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#137 fix: get started button anchor
  config.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#140 edited the content for clarity and completeness
  content/en/docs/event-sources/kubernetes-audit.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#143 edited the content to give clarity and fix broken links
  content/en/docs/event-sources/dropped-events.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#134 new: document the new FALCO_BPF_PROBE variable
  content/en/docs/installation.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/M

#145 chore(content/en/blog): typo
  content/en/blog/falco-0-20-0.md
Labels: approved, area/blog, dco-signoff: yes, kind/cleanup, kind/content, lgtm, size/XS

#147 Fix image tag version in documentation
  config.yaml
  content/en/docs/installation.md
  content/en/docs/running.md
  content/en/docs/source.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/S

#150 fix(content/en/docs/event-sources): correct link to config
  content/en/docs/event-sources/dropped-events.md
Labels: approved, area/documentation, dco-signoff: yes, kind/bug, kind/content, lgtm, size/XS

#152 Use shortcodes for version insertion
  content/en/docs/installation.md
  content/en/docs/source.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#154 fix wrong tld for sysdig domain
  content/en/docs/rules/_index.md
Labels: approved, area/documentation, dco-signoff: yes, kind/bug, lgtm, size/XS
