Repository falcosecurity/falco-website, pull requests merged in 2021-06, with the labels that each got.

#436 Update contributor-of-the-month.md
  content/en/docs/contribute/contributor-of-the-month.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#438 Detect Malicious Behaviors Through Audit Logs - blog post
  content/en/blog/falco-detect-malicious-behavior-through-audit-logs.md
  content/en/docs/images/falcosidekick_web_ui_detect-malicious_behavior_through-audit-logs.png
Labels: approved, dco-signoff: yes, lgtm, size/XL

#439 build: upgrade deps
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XXL

#445 Fix link to events generator project
  content/en/docs/event-sources/sample-events.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#448 blog for i18n process
  content/en/blog/falco-i18n.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#450 changed a section heading to a crispy one
  content/en/blog/falco-i18n.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#451 Update contributor-of-the-month.md
  content/en/docs/contribute/contributor-of-the-month.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#452 Language and style edit to improve readability
  content/en/blog/falco-i18n.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#454 Revamp exceptions docs
  content/en/docs/rules/exceptions.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/L

#457 new(content/en/blog): 0.29.0 release
  content/en/blog/falco-0-29-0.md
Labels: approved, area/blog, dco-signoff: yes, kind/content, lgtm, size/L

#464 malayalam translation for rules files
  content/ml/docs/rules/_index.md
  content/ml/docs/rules/default-custom.md
  content/ml/docs/rules/default-macros.md
  content/ml/docs/rules/exceptions.md
  content/ml/docs/rules/supported-fields.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#465 language review for readablity
  content/en/blog/falcosidekick-reponse-engine-part-1-kubeless.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#468 translation for configuration and contribute directories
  content/ml/docs/configuration/_index.md
  content/ml/docs/contribute/_index.md
  content/ml/docs/contribute/contributor-of-the-month.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#446 Blog post about Kubernetes Response Engine with Google Cloud Run - Part 6
  content/en/blog/falcosidekick-reponse-engine-part-6-cloud-run.md
  content/en/docs/images/cloud_run_function_outout.png
  content/en/docs/images/cloud_run_reference_arch.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#461 Add examples of running falco-no-driver and falco-driver-loader in fully privileged mode and reasons why one might want to
  content/en/docs/getting-started/running.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/M

#472 Updated GitLab URL
  config.toml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#453 Kubernetes Response Engine, Part 7: Falcosidekick + Cloud Functions
  content/en/blog/falcosidekick-reponse-engine-part-7-cloud-functions.md
  content/en/docs/images/cloud_function_output.png
  content/en/docs/images/cloud_functions_reference_arch.png
Labels: approved, area/blog, dco-signoff: yes, kind/content, lgtm, size/XL
