Repository falcosecurity/falco-website, pull requests merged in 2021-02, with the labels that each got.

#388 Install kernel headers for Arch Linux
  content/en/docs/getting-started/source.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/XS

#389 Fix "audit-webhook-config-file" argument name
  content/en/docs/event-sources/kubernetes-audit.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#390 Fix broken url in docs
  content/en/docs/getting-started/third-party/learning.md
Labels: approved, area/documentation, dco-signoff: yes, lgtm, size/XS

#385 chore: fix broken links
  content/en/docs/alerts/_index.md
  content/ja/docs/alerts/_index.md
Labels: approved, area/documentation, dco-signoff: yes, kind/cleanup, lgtm, size/XS
