Repository falcosecurity/falco-website, pull requests merged in 2021-04, with the labels that each got.

#409 [translation] Malayalam Translation for Falco Alert Documentation
  content/ml/docs/alerts/_index.md
  content/ml/docs/alerts/formating.md
  content/ml/docs/getting-started/third-party/_index.md
  content/ml/docs/getting-started/third-party/install-tools.md
  content/ml/docs/getting-started/third-party/learning.md
  content/ml/docs/getting-started/third-party/production.md
Labels: approved, area/documentation, dco-signoff: yes, kind/translation, lgtm, size/XL

#417 Add upgrade guide for openSUSE
  content/en/docs/getting-started/upgrade.md
Labels: approved, area/documentation, dco-signoff: yes, kind/content, lgtm, size/S

#412 Use git --depth and --branch flags to save space/time
  content/en/blog/falco-wsl2-custom-kernel.md
Labels: approved, area/documentation, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#418 update blog post extend falco with falcosidekick
  content/en/blog/extend-falco-outputs-with-falcosidekick.md
  static/img/falcosidekick-slack-test.png
  static/img/falcosidekick-slack-test2.png
  static/img/falcosidekick-slack-test3.png
  static/img/falcosidekick-ui-1.png
  static/img/falcosidekick-ui-2.png
Labels: approved, area/blog, dco-signoff: yes, kind/content, lgtm, size/L

#419 add Frank
  content/en/docs/contribute/contributor-of-the-month.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#420 added Get Involved details
  content/en/blog/extend-falco-outputs-with-falcosidekick.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#421 Update for April 2021
  content/en/docs/contribute/contributor-of-the-month.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#415 [Blog] OpenFaaS output type blog post ready
  content/en/blog/falcosidekick-openfaas.md
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#424 little fixes about openfaas output type blog post
  content/en/blog/falcosidekick-openfaas.md
Labels: approved, dco-signoff: yes, lgtm, size/S
