Repository falcosecurity/falco-website, pull requests merged in 2022-11, with the labels that each got.

#721 blog post about the K8SAudit EKS logs plugin
  content/en/blog/falco-plugin-k8saudit-eks.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L

#723 new(blog): Falco at the KubeCon 2022
  content/en/blog/falco-at-kubecon-na-2022/images/falco-at-kubecon-na-2022-01.png
  content/en/blog/falco-at-kubecon-na-2022/images/falco-at-kubecon-na-2022-03.png
  content/en/blog/falco-at-kubecon-na-2022/images/falco-at-kubecon-na-2022-04.png
  content/en/blog/falco-at-kubecon-na-2022/images/falco-at-kubecon-na-2022-featured.png
  content/en/blog/falco-at-kubecon-na-2022/index.md
  layouts/shortcodes/youtube-80.html
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#700 Remove explicit h1/# from documentation pages
  content/en/docs/event-sources/dropped-events.md
  content/en/docs/event-sources/kubernetes-audit.md
  content/en/docs/event-sources/okta.md
  content/en/docs/plugins/_index.md
  content/en/docs/rules/conditions.md
  content/en/docs/rules/exceptions.md
  content/en/docs/rules/fd-sip-name.md
  content/en/docs/rules/supported-fields.md
Labels: kind/design, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#724 update: containerize translations into directories
  i18n/en/en.yaml
  i18n/ja/ja.yaml
  i18n/ko/ko.yaml
  i18n/ml/ml.yaml
  i18n/zh-cn/zh-cn.yaml
Labels: lgtm, size/XS, dco-signoff: yes, approved, kind/translation, area/blog, area/documentation

#679 new(.github): add dependabot
  .github/dependabot.yml
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved

#728 docs(blog): Falco applies for graduation
  content/en/blog/falco-applies-for-graduation.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#734 add video to falco kubecon post
  content/en/blog/falco-at-kubecon-na-2022/index.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#730 update(netlify build): NPM version to 9.1.1
  netlify.toml
Labels: kind/design, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#733 update(docs): version params
  config/_default/config.toml
  config/_default/versions/params.yaml
  content/en/docs/supported-doc-versions.md
  i18n/en/supported-versions/en.yaml
  layouts/docs/supported-versions.html
  layouts/partials/docs/content-page.html
  release.md
Labels: lgtm, dco-signoff: yes, approved, size/XL

#744 update(config): update version number for 0.33.1
  config/_default/versions/params.yaml
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#743 new(blog): add entry for Falco 0.33.1
  content/en/blog/falco-0-33-1.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#736 new docs/reference section
  content/en/docs/reference/_index.md
  layouts/partials/page-meta-links.html
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#739 add tutorials section
  content/en/docs/tutorials/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#745 add(header): fields canonicalURL/canonical_url to Frontmatter
  layouts/partials/head.html
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#738 move changelog section under reference
  content/en/docs/reference/changelog/index.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#759 new(blog): Falco on AWS Cloud
  content/en/blog/falco-on-aws.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#760 new(site) default featured image
  config/_default/config.toml
  static/images/featured/default-01.png
Labels: kind/design, lgtm, size/XS, dco-signoff: yes, approved, area/blog
