Repository falcosecurity/falco-website, pull requests merged in 2022-02, with the labels that each got.

#540 fix: docker cap name is BPF not SYS_BPF
  content/en/docs/getting-started/running.md
  content/ja/docs/getting-started/running.md
  content/ml/docs/getting-started/running.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#543 Small changes to rules page related to plugins/event sources
  content/en/docs/rules/_index.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#544 update(OWNERS): add jasondellaluce
  OWNERS
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#525 update: mouting /dev is not needed for eBPF
  content/en/docs/getting-started/running.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#545 new blog post: Announcing Plugins and Cloud Security with Falco
  content/en/blog/announcing_plugins_and_cloud_security_with_falco.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#547 fix: typo in the running and plugin dev-guide sections
  content/en/docs/getting-started/running.md
  content/en/docs/plugins/developers-guide.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#546 Extend Falco inputs by creating a Plugin: the basics
  content/en/blog/extend-falco-inputs-with-a-plugin-the-basics.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/XXL

#555 Update userspace instrumentation Link.
  content/en/docs/getting-started/running.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#552 Update installation.md by adding an specific command for amzn2
  content/en/docs/getting-started/installation.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#556 Fixed a typo in the document.From filees to files.
  content/en/docs/rules/_index.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#558 add links to community calls records
  config.toml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#559 docs(content): ncurses is not required anymore
  content/en/docs/getting-started/source.md
  content/ja/docs/getting-started/source.md
  content/ko/docs/source.md
  content/ml/docs/getting-started/source.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M
