Repository falcosecurity/falco-website, pull requests merged in 2022-04, with the labels that each got.

#572 docs: remove PSP support section
  content/en/docs/psp-support/_index.md
  content/ja/docs/psp-support/_index.md
  content/ko/docs/psp-support/_index.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/XL

#578 docs: add stdout buffering explanation
  content/en/docs/alerts/_index.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#579 fix: updating eBPF probe minimum kernel version guidance
  content/en/blog/choosing-a-driver.md
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation
