Repository falcosecurity/falco-website, pull requests merged in 2022-06, with the labels that each got.

#610 fix(docs): repo url for Terraform AWS CloudTrail module
  content/en/docs/event-sources/cloudtrail.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#611 update(config): archive 0.31.
  config/_default/config.toml
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#608 update(config): updated website config for 0.32.0.
  config/_default/config.toml
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/blog

#606 new(content): added Falco 0.32 blog post
  content/en/blog/falco-0-32-0.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#607 new(content): updated supported events for 0.32.0.
  content/en/docs/rules/supported-events.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#612 docs: change order of instruction steps for website snapshot
  release.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#599 Fix first time make serve command fail due to not downloaded submodules
  Makefile
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#613 Display the CRI options where K3s is used
  content/en/docs/getting-started/third-party/production.md
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#619 add `bcontains` and `bstartswith` to the table of operators
  content/en/docs/rules/conditions.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#617 update(docs): update supported fields for 0.32.0
  content/en/docs/rules/supported-fields.md
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#604 add contribution-drivers-kmod-ebpf-libraries.md
  content/zh/blog/contribution-drivers-kmod-ebpf-libraries.md
Labels: lgtm, dco-signoff: yes, approved, size/M

#602 Add cloud-native-security-hub.md
  content/zh/blog/cloud-native-security-hub.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#625 Sepcifying how to check bpf_jit_enable is set to 1
  content/en/docs/getting-started/installation.md
Labels: lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#633 falco-0-21-0.md file translate Chinese
  content/zh/blog/falco-0-21-0.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#634 falco-0-22-x.md file translate Chinese
  content/zh/falco-0-22-x.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#635 falco-0-23-0.md file translate Chinese
  content/zh/falco-0-23-0.md
Labels: lgtm, dco-signoff: yes, approved, size/M

#631 docs(content/docs/plugins): document Go SDK source instance prebuilts
  content/en/docs/plugins/go-sdk-walkthrough.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#638 falco-0-25-0.md file translate Chinese
  content/zh/blog/falco-0-25-0.md
Labels: lgtm, dco-signoff: yes, approved, size/M

#636 falco-0-25-0.md file translate Chinese
  content/zh/falco-0-25-0.md
Labels: lgtm, dco-signoff: yes, approved, size/M
