Repository falcosecurity/falco-website, pull requests merged in 2022-10, with the labels that each got.

#695 update(docs): use the correct helm options based on v2.0.0 of the faco chart
  content/en/docs/getting-started/third-party/production.md
Labels: lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#709 update(content/docs): correct dummy plugin Go source code link
  content/en/docs/plugins/go-sdk-walkthrough.md
Labels: kind/cleanup, kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#710 update(learning.md): sync with docs changes of Falco 0.33.0 about minikube
  content/en/docs/getting-started/third-party/learning.md
Labels: lgtm, dco-signoff: yes, approved, size/M

#659 Update docs for json_output option to reflect alerts+rules result v2
  data/en/config.yaml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#699 chore(content): updated running page with newest informations.
  content/en/docs/getting-started/running/_index.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#702 update(content/en/docs): refresh list of syscall events for Falco 0.33.0
  content/en/docs/rules/supported-events.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#704 update(content/en/docs): sync supported field list with Falco 0.33
  content/en/docs/rules/supported-fields.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#706 update(content/en/docs): sync plugin api reference with Falco v0.33
  content/en/docs/plugins/plugin-api-reference.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#714 update(config.toml): update website to v0.33
  config/_default/config.toml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#716 new(content/en/blog): add post for Falco 0.33
  content/en/blog/falco-0-33-0.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#717 update(learning/minikube): docs to deploy falco with syscall and k8saudit on minikube
  content/en/docs/getting-started/third-party/learning.md
Labels: lgtm, dco-signoff: yes, approved, size/XL

#718 new(blog): Using Falco to Protect GitHub
  content/en/blog/falco-plugin-github/images/falco-plugin-github-01.png
  content/en/blog/falco-plugin-github/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#719 update(learning): add a command in minikube doc
  content/en/docs/getting-started/third-party/learning.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#720 update(docs/minikube): avoid extra steps during the creation of config files
  content/en/docs/getting-started/third-party/learning.md
Labels: lgtm, dco-signoff: yes, approved, area/documentation, size/M
