Repository falcosecurity/falco-website, pull requests merged in 2022-07, with the labels that each got.

#603 Add detect-cve-2020-8557.md Chinese file
  content/zh/blog/detect-cve-2020-8557.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#621 extend-falco-outputs-with-falcosidekick.md file translate Chinese
  content/zh/extend-falco-outputs-with-falcosidekick.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#624 display the Author Name in the list of Blog posts
  layouts/blog/list.html
Labels: kind/design, lgtm, dco-signoff: yes, approved, area/blog, size/M

#629 extend-falco-inputs-with-a-plugin-the-basics.md file translate Chinese
  content/zh/extend-falco-inputs-with-a-plugin-the-basics.md
Labels: lgtm, dco-signoff: yes, approved, size/XXL

#640 Modify the file falco-0-25-0.md to falco-0-26-1.md
  content/zh/blog/falco-0-26-1.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#641 falco-0-24-0.md file translation Chinese
  content/zh/blog/falco-0-24-0.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#644 falco-0-26-2.md file translation Chinese
  content/zh/blog/falco-0-26-2.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#643 add last modification date under title in its short version
  layouts/_default/content.html
  layouts/docs/list.html
  layouts/partials/page-meta-lastmod-short.html
Labels: kind/user-interface, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#645 update blog post Extend Falco inputs by creating a Plugin: the basics
  .vscode/settings.json
  content/en/blog/extend-falco-inputs-with-a-plugin-the-basics.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/XXL

#648 update(docs): update config.toml for v0.32.1
  config/_default/config.toml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#654 update(blog): fix minor typo on 0.32.1 post
  content/en/blog/falco-0-32-1.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/blog

#656 update(docs): update the example url at DaemonSet on Kubernetes Deployment Document
  content/en/docs/getting-started/deployment.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#657 Update docs for json_output option to reflect alerts+rules result
  data/en/config.yaml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#658 Revert "Update docs for json_output option to reflect alerts+rules re…
  data/en/config.yaml
Labels: lgtm, size/XS, dco-signoff: yes, approved

#651 falco-0-27-0.md file translation Chinese
  content/zh/blog/falco-0-27-0.md
Labels: lgtm, dco-signoff: yes, approved, size/M

#652 falco-0-28-1.md file translation Chinese
  content/zh/blog/falco-0-28-1.md
Labels: lgtm, dco-signoff: yes, approved, size/M
