Repository falcosecurity/falco-website, pull requests merged in 2023-10, with the labels that each got.

#1171 fix(content): remove en -> international links to pages
  content/ja/community/contributors.md
  content/ja/community/events.md
  content/ja/community/falco-brand.md
  content/ja/docs/reference
  content/ko/community/contributors.md
  content/ko/community/events.md
  content/ko/community/falco-brand.md
  content/ko/docs/reference
  content/ml/community/contributors.md
  content/ml/community/events.md
  content/ml/community/falco-brand.md
  content/ml/docs/reference
  content/zh-cn/community/contributors.md
  content/zh-cn/community/events.md
  content/zh-cn/community/falco-brand.md
  content/zh-cn/docs/reference
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1169 fix(blog): fix typos/ambiguous sentence in 0.36.0 blog
  content/en/blog/falco-0-36-0/index.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/blog

#1173 adds second part of the blog tracing system calls using ebpf
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-01.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-02.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-03.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-04.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-05.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/images/ebpf2-blog-featured.png
  content/en/blog/tracing-system-calls-using-ebpf-part-2/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#1179 fix: add environment separation for development and archived branches
  Makefile
  netlify.toml
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1181 unset production environment for archived branch v0.35
  Makefile
  netlify.toml
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1184 unset production environment for archived branch 0.33
  Makefile
  netlify.toml
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1185 unset production environment for archived branch 0.32
  Makefile
  netlify.toml
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1183 unset production environment for archived branch 0.34
  Makefile
  netlify.toml
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1186 set noindex and nofollow for archived branch 0.26
  themes/falco-fresh/layouts/partials/meta.html
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, area/documentation

#1187 new(blog): add a blog post for Falco 0.36.1
  content/en/blog/falco-0-36-1/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1188 update(config): update version number to 0.36.1
  config/_default/versions/params.yaml
Labels: kind/design, lgtm, size/XS, dco-signoff: yes, approved
