Repository falcosecurity/falco-website, pull requests merged in 2023-04, with the labels that each got.

#909 update section about IAM
  content/en/blog/falco-aws-security-lake/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#910 fix: responsive layout
  assets/scss/_community.scss
  assets/scss/_variables_project.scss
  layouts/community/list.html
  static/img/community/_falco_flock.jpg
  static/img/community/falco_flock.jpg
Labels: kind/bug, kind/design, lgtm, dco-signoff: yes, approved, size/L

#917 fix: add some spaces after pageinfo
  content/en/docs/getting-started/third-party/learning.md
Labels: kind/bug, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#923 feat: update contribute content, update keywords
  content/en/about/falco.md
  content/en/about/use-cases.md
  content/en/community/contributors.md
  layouts/community/contributors.html
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L

#915 adding march 2023 contributor of the month
  data/contributors.yaml
Labels: kind/user-interface, kind/content, lgtm, dco-signoff: yes, size/S, approved

#916 fix: copy blog link quotes
  layouts/blog/content.html
  layouts/partials/blog/card.html
Labels: lgtm, size/XS, dco-signoff: yes, approved

#921 fix: add property to css to fix incorrect scroll position
  assets/scss/_utilities.scss
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved

#926 feat: about ecosystem responsive layout
  assets/scss/_tabs.scss
  content/en/about/ecosystem.md
  layouts/shortcodes/blocks/tabs.html
  layouts/shortcodes/footer_nav.html
Labels: kind/user-interface, lgtm, dco-signoff: yes, approved, size/M

#927 feat: add keywords
  content/en/about/falco.md
  content/en/about/use-cases.md
  layouts/partials/head.html
Labels: lgtm, size/XS, dco-signoff: yes, approved

#928 fix: center the navbar menu items
  layouts/partials/navbar.html
Labels: kind/design, kind/user-interface, lgtm, size/XS, dco-signoff: yes, approved

#922 feat: change width of the content
  content/en/about/use-cases.md
Labels: kind/user-interface, kind/content, lgtm, dco-signoff: yes, size/S, approved

#930 fix: accessibility of why-falco
  layouts/partials/announcement-bar.html
  layouts/partials/navbar.html
  layouts/shortcodes/content_arrow.html
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved

#931 fix: update about, community sections accessibility
  assets/js/community-videos.js
  assets/js/events.js
  content/en/about/ecosystem.md
  layouts/partials/footer.html
Labels: lgtm, dco-signoff: yes, size/S, approved

#935 fix: remove content from events.md
  content/en/community/events.md
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved

#936 feat: added get videos to functions
  assets/js/community-videos.js
  assets/js/videos.js
  functions/youtube-bypass.js
Labels: kind/bug, lgtm, dco-signoff: yes, approved, size/M

#937 feat: faq cards
  content/en/about/ecosystem.md
  content/en/about/falco.md
  content/en/about/faq.md
  content/en/about/use-cases.md
  content/en/about/why-falco.md
  layouts/partials/card_faq.html
  layouts/shortcodes/card_faq.html
  layouts/shortcodes/feedback.html
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, size/L

#938 fix: landing page events script restored
  assets/js/events.js
  layouts/partials/community/events.html
  layouts/partials/landing/events.html
Labels: lgtm, dco-signoff: yes, approved, size/L

#940 feat: add falco-brand page
  assets/scss/_card.scss
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  config/_default/config.toml
  content/en/community/falco-brand.md
  data/colors.yaml
  data/en/facts.yaml
  data/en/slideTemplates.yaml
  data/logos.yaml
  layouts/community/falco-brand.html
  layouts/partials/brand-logos.html
  layouts/partials/colors.html
  layouts/partials/project-facts.html
  layouts/partials/slide-templates.html
  static/icons/check-sm.svg
  static/icons/collection-fill.svg
  static/icons/collection.svg
  static/icons/diagram-fill.svg
  static/icons/play-circle-fill.svg
  static/icons/x-stroke.svg
  static/img/brand/falco-horizontal-black.png
  static/img/brand/falco-horizontal-black.svg
  static/img/brand/falco-horizontal-color.png
  static/img/brand/falco-horizontal-color.svg
  static/img/brand/falco-horizontal-white.png
  static/img/brand/falco-horizontal-white.svg
  static/img/brand/falco-icon-black.png
  static/img/brand/falco-icon-black.svg
  static/img/brand/falco-icon-color.png
  static/img/brand/falco-icon-color.svg
  static/img/brand/falco-icon-white.png
  static/img/brand/falco-icon-white.svg
  static/img/brand/falco-stacked-black.png
  static/img/brand/falco-stacked-black.svg
  static/img/brand/falco-stacked-color.png
  static/img/brand/falco-stacked-color.svg
  static/img/brand/falco-stacked-white.png
  static/img/brand/falco-stacked-white.svg
Labels: kind/design, kind/user-interface, lgtm, dco-signoff: yes, approved, size/XXL

#944 fix: added faq card copy link button
  assets/js/copy-link.js
  assets/scss/_card.scss
  layouts/_default/baseof.html
  layouts/partials/card_faq.html
Labels: lgtm, dco-signoff: yes, approved, size/M

#947 fix: update font size
  layouts/community/falco-brand.html
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved

#945 fix: change url of about falco page
  config/_default/config.toml
  content/en/about/_index.md
  content/en/about/falco.md
Labels: kind/user-interface, lgtm, dco-signoff: yes, approved, size/L

#941 fix: correct link to gRPC certificates config
  content/en/blog/falco-kind-prometheus-grafana.md
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#942 update AWS Security Lake blog post for GA
  content/en/blog/falco-aws-security-lake/images/aws_security_lake_custom_source.png
  content/en/blog/falco-aws-security-lake/images/aws_security_lake_s3.png
  content/en/blog/falco-aws-security-lake/index.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#946 fix: nominations logic
  data/nominations.yaml
  layouts/partials/nominations.html
Labels: kind/bug, lgtm, dco-signoff: yes, approved, size/M

#816 fix: improve Debian instructions
  content/en/docs/getting-started/installation.md
Labels: lgtm, dco-signoff: yes, size/S, approved, area/documentation
