Repository falcosecurity/falco-website, pull requests merged in 2024-08, with the labels that each got.

#1353 fix: update sysdig training links
  config/_default/params.toml
  data/training/offerings/detect-cryptomining.yaml
  data/training/offerings/falco-101.yaml
  data/training/offerings/falco-plugins.yaml
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation, area/community

#1350 new(blog): add falco 0.38.2 blog
  content/en/blog/falco-0-38-2/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1349 update(metrics): describe prometheus metrics changes for Falco 0.38.2
  content/en/docs/metrics/falco-metrics.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#1355 update(config): add 0.38.2
  config/_default/versions/params.yaml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1354 fix(docs): update rules setup documentation
  content/en/docs/reference/rules/default-rules/index.md
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation
