Repository falcosecurity/falco-website, pull requests merged in 2024-01, with the labels that each got.

#1228 fix: fix a broken link in the modern bpf section
  content/en/docs/event-sources/kernel/_index.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1236 adding the missing /etc:/host/etc:ro for modern-bpf
  content/en/docs/install-operate/running/index.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#1237 Update fspath.md
  content/en/docs/rules/fspath.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#1241 add tracking pixels from scarf to follow the users journeys in the we…
  config/_default/config.toml
  layouts/_default/baseof.html
  layouts/blog/baseof.html
  layouts/docs/baseof.html
Labels: kind/design, lgtm, size/XS, dco-signoff: yes, approved, area/blog, area/documentation, area/community

#1255 correct 1-char typo in the word Examine
  content/en/docs/getting-started/linux-quickstart.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#1243 fix(docs): update grpc output socket name
  content/en/blog/falco-performance-testing.md
  content/en/docs/grpc/grpc-config.md
  content/ja/blog/falco-performance-testing.md
  content/ml/docs/grpc/_index.md
  data/en/reference/daemon/config_options.yaml
Labels: kind/cleanup, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1245 update: add x86_64 emulated VM option to apple silicon guide
  content/en/blog/falco-m1.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1257 See PR 1203
  content/en/docs/install-operate/installation.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, approved, size/M

#1260 chore(config): update website version
  config/_default/versions/params.yaml
Labels: lgtm, dco-signoff: yes, size/S, approved

#1258 update(docs): update CLI args for Falco 0.37.0
  content/en/docs/reference/daemon/cli-arguments/cli-arguments.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#1252 cleanup(docs): add some deprecation warnings
  content/en/docs/event-sources/enable-event-sources.md
  content/en/docs/install-operate/third-party/learning.md
  content/en/docs/rules/controlling-rules.md
  content/en/docs/rules/exceptions.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1262 cleanup(blog): fix indentation in Falco 0.37.0 blog post
  content/en/blog/falco-0-37-0/index.md
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/blog

#1263 update(docs): update k8s fields description
  content/en/docs/reference/rules/supported-fields/supported-fields.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation
