Repository falcosecurity/falco-website, pull requests merged in 2024-04, with the labels that each got.

#1267 Falco network security
  content/en/blog/falco-network-security/index.md
Labels: lgtm, size/XS, dco-signoff: yes, approved, area/blog

#1307 update(content): remove old config options from documentation page
  data/en/reference/daemon/config_options.yaml
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1304 create gvisor docs
  content/en/docs/event-sources/gvisor/_index.md
  content/en/docs/event-sources/gvisor/images/gvisor-01.png
  content/en/docs/event-sources/gvisor/images/gvisor-02.png
  content/en/docs/event-sources/gvisor/images/gvisor-webinar.png
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#1311 update(content): add Display attribute to plugin post
  content/en/blog/extend-falco-inputs-with-a-plugin-the-basics.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1312 fix(docs): fix example command indentation
  content/en/docs/getting-started/linux-quickstart.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1313 update(learning/minikube): update minikube tutorial
  content/en/docs/install-operate/third-party/learning.md
Labels: lgtm, dco-signoff: yes, approved, size/L

#1315 replace the sysdig logo
  layouts/index.en.html
  layouts/partials/footer.html
  static/icons/sysdig.svg
  static/images/training/providers/sysdig.svg
  static/img/adopters/sysdig.png
  static/img/created-by-sysdig.png
  static/img/training/sysdig.png
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, size/M
