Repository falcosecurity/falco-website, pull requests merged in 2024-02, with the labels that each got.

#1264 update(docs): update build from source page
  content/en/docs/install-operate/source.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#1269 new(content): added blog post for Falco 0.37.1 patch release.
  content/en/blog/falco-0-37-1/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1271 chore(docs): falco-no-driver still needs etc volume.
  content/en/docs/install-operate/running/index.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1272 new(content): added weekly recap w7 2024.
  content/en/blog/falco-week-7-2024/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1273 fix(layouts): footer spacing
  layouts/_default/baseof.html
  layouts/blog/baseof.html
  layouts/docs/baseof.html
Labels: kind/bug, kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved

#1274 add anchors to allow to share a rule with a link
  layouts/shortcodes/rules_list.html
Labels: kind/cleanup, kind/user-interface, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1275 update plugged videos in landing page
  data/videos.yaml
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved

#1277 new(blog): add entry for Falco graduation
  content/en/blog/falco-graduation/images/falco-graduation-featured.png
  content/en/blog/falco-graduation/index.md
Labels: lgtm, dco-signoff: yes, approved, area/blog, size/M, kind/event

#1278 update(content): incubating->graduated
  content/en/about/_index.md
  i18n/en/en.yaml
  i18n/ja/ja.yaml
  i18n/ko/ko.yaml
  i18n/zh-cn/zh-cn.yaml
  layouts/community/falco-brand.html
Labels: kind/content, lgtm, dco-signoff: yes, size/S, approved, area/documentation

#1279 new(website): add sticky graduation announcement
  assets/js/announcement-bar.js
  assets/scss/_announcement.scss
  data/en/announcements/graduation.yaml
  layouts/_default/baseof.html
  layouts/blog/baseof.html
  layouts/docs/baseof.html
  layouts/partials/announcement-bar.html
  static/icons/cncf-icon-color.svg
  static/icons/falco-icon-color.svg
Labels: kind/user-interface, lgtm, dco-signoff: yes, approved, size/L, area/documentation

#1280 fix(blog): add missing quote to graduation blog
  content/en/blog/falco-graduation/index.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/blog

#1281 fix(blog): falco graduation image metadata
  content/en/blog/falco-graduation/index.md
Labels: kind/bug, lgtm, size/XS, dco-signoff: yes, approved, area/blog

#1282 update the image for the social network sharings
  static/images/featured/default-01.png
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved
