Repository falcosecurity/falco-website, pull requests merged in 2024-12, with the labels that each got.

#1417 blog post falcosidekick 2.30.0
  content/en/blog/falcosidekick-2-30-0/images/falcosidekick-featured.png
  content/en/blog/falcosidekick-2-30-0/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M

#1420 update(docs): rust plugin sdk link
  content/en/docs/plugins/architecture.md
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1423 Fix "Checkout Falcoctl Repo" stage in the GH action
  content/en/docs/plugins/developers-guide/how-to-distribute.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#1424 Fix the runs-on field in the "release" stage
  content/en/docs/plugins/developers-guide/how-to-distribute.md
Labels: lgtm, size/XS, dco-signoff: yes, approved

#1425 Update plugin docs, add missing "plugin_" prefixes
  content/en/docs/reference/plugins/plugin-api-reference.md
Labels: kind/bug, lgtm, dco-signoff: yes, size/S, approved, area/documentation
