Repository falcosecurity/falco-website, pull requests merged in 2025-02, with the labels that each got.

#1445 Update grpc-config.md
  content/en/docs/developer-guide/grpc/grpc-config.md
Labels: lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1446 Add NETWAYS Web Services to the ecosystem page
  data/adopters/endusers/nws.yaml
  static/img/adopters/nws.png
Labels: kind/content, lgtm, size/XS, dco-signoff: yes, approved, area/community

#1448 blog post falco-talon 0.3.0
  content/en/blog/falco-talon-v0-3-0/images/falco-talon-featured.png
  content/en/blog/falco-talon-v0-3-0/images/minio.png
  content/en/blog/falco-talon-v0-3-0/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, area/blog, size/M
