Repository falcosecurity/falco-website, pull requests merged in 2025-05, with the labels that each got.

#1467 ignore and cleanup vim swp files
  .gitignore
  content/en/blog/atomic-red-falco/.index.md.swp
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved

#1468 Fix broken Golang SDK link
  content/en/docs/developer-guide/grpc/_index.md
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1471 update(docs): include field/event update in the release document
  release.md
Labels: kind/cleanup, lgtm, size/XS, dco-signoff: yes, approved, area/documentation

#1476 new(content): added Falco 0.41.0 blog post.
  content/en/blog/falco-0-41.0/index.md
Labels: kind/content, lgtm, dco-signoff: yes, approved, size/L, area/blog

#1474 update(content): typo pass
  content/en/docs/concepts/event-sources/plugins/_index.md
  content/en/docs/concepts/outputs/_index.md
  content/en/docs/concepts/rules/fd-sip-name.md
  content/en/docs/concepts/rules/fspath.md
  content/en/docs/developer-guide/plugins/how-to-develop.md
  content/en/docs/reference/plugins/go-sdk-walkthrough.md
  content/en/docs/reference/plugins/plugin-api-reference.md
  content/en/docs/reference/rules/rule-fields/rule-fields.md
  content/en/docs/setup/container.md
  content/en/docs/setup/kubernetes.md
  content/en/docs/setup/packages.md
  content/en/docs/setup/tarball.md
Labels: kind/cleanup, kind/content, lgtm, dco-signoff: yes, approved, area/documentation, size/M

#1477 update(metrics): sync page for Falco 0.41.0 release
  content/en/docs/concepts/metrics/_index.md
Labels: kind/cleanup, lgtm, dco-signoff: yes, approved, area/documentation, size/XXL
